### ISSUE TITLE
error CS0234: The type or namespace name 'NpgsqlSnakeCaseNameTranslator' does not exist in the namespace 'Npgsql' 

### ISSUE THREAD

**Issue by araneta** [nbarbettini/QuestionExchange#2]
I got this error 
AppDbContext.cs(19,28): error CS0234: The type or namespace name 'NpgsqlSnakeCaseNameTranslator' does not exist in the namespace 'Npgsql' (are you missing an assembly reference?)
when compiling this project dotnet run

**Comment by nbarbettini** [comment]
Did you install the `Npgsql.EntityFrameworkCore.PostgreSQL` package? Try `dotnet restore` before running the project. Let me know if you are still stuck.
