### ISSUE TITLE
Error in AppDbContext

### ISSUE THREAD

**Issue by girishnuli** [nbarbettini/QuestionExchange#3]
In the AppDbContext, the below line throws an error. Where is the method NpgsqlSnakeCaseNameTranslator() coming from? Is it an extension method?

var mapper = new Npgsql.NpgsqlSnakeCaseNameTranslator();

Correct nuget package is added to the project: 
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.1.2" />

Thanks

**Comment by nbarbettini** [comment]
Sorry for the long delay, I'm cleaning out old issues and came across this. Apologies for not answering it back in 2018!

NpgsqlSnakeCaseNameTranslator is part of the Npgsql package: https://www.npgsql.org/doc/api/Npgsql.NameTranslation.NpgsqlSnakeCaseNameTranslator.html
